# Generated by Django 5.0.2 on 2024-03-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='book_images/'),
        ),
    ]
